language: python
python:
  - 2.7
  - 3.5
  - 3.6
  # To see available versions:
  #   s3cmd ls s3://travis-python-archives/binaries/ubuntu/14.04/x86_64/
  - pypy2.7-5.8.0
  - pypy3.5-5.8.0
sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      language: python
      python: 3.6
      env: DOC_BUILD=1

script:
  - ci/travis.sh
